name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Jalankan setiap hari pada pukul 00:00 UTC
  workflow_dispatch:  # Bisa juga dijalankan secara manual

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/lakuapik/jadwalsholatorg.git
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit
          git push origin main
          
