name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Jalankan setiap hari pada pukul 00:00 UTC
  workflow_dispatch:  # Bisa juga dijalankan secara manual

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/lakuapik/jadwalsholatorg.git || git remote set-url upstream https://github.com/OWNER/REPO.git
          git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout master  # Ganti 'main' dengan 'master'
          git merge --ff-only upstream/master || echo "No changes to merge"

      - name: Push Changes to Fork
        run: |
          git push origin master || echo "No changes to push"

      - name: Commit and Push changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "[gh-actions] update fork"
            git push origin master
          else
            echo "No changes to commit"
          fi
          
